OboPlayground\Domain\Model\User:
    type: entity
    repositoryClass: OboPlayground\Infrastructure\Repository\User\UserRepositoryDoctrineBase
    id:
        user_id:
            type: guid
            strategy: NONE
    fields:
        email:
            type: string
            length: 255
        name:
            type: string
            length: 255
