OboPlayground\Domain\Model\Department\Department:
    type: entity
    table: department
    id:
        id:
            type: department_id
    fields:
        name:
            type: string
            length: 255
